export const topTen = [{"name": "Apple", "ticker": "AMZN", "price": 107.4, "Today": 3.35},
{"name": "NVIDIA Corp", "ticker": "NVDA", "price": 159.82, "Today": -6.36},
{"name": "Shopify", "ticker": "SHOP", "price": 31.41, "Today": 0.17},
{"name": "Redfin Corp", "ticker": "RDFN", "price": 8.96, "Today": 0.72},
{"name": "Apple", "ticker": "AAPL", "price": 138.93, "Today": 2.21},
{"name": "Ericsson", "ticker": "ERIC", "price": 7.43, "Today": 0.03},
{"name": "Palo Alto Networks Inc", "ticker": "PANW", "price": 508.25, "Today": 14.31},
{"name": "Roku Inc", "ticker": "ROKU", "price": 83.91, "Today": 1.77},
{"name": "Tesla Inc", "ticker": "TSLA", "price": 681.79, "Today": 1.24},]


export const creator = [{"name": "Alphabet Inc", "ticker": "GOOGL", "price": 2174.75, "Today": -4.51},
{"name": "NVIDIA Corp", "ticker": "NVDA", "price": 159.82, "Today": -6.36},
{"name": "Nike, Inc", "ticker": "NKE", "price": 101.18, "Today": -1.02},
{"name": "McLaren Technology Acquisition Corp", "ticker": "MLAI", "price": 10.01, "Today": 0.00}]

export const mostpop = [
    {"name": "Apple Inc", "ticker": "AAPL", "price": 138.93, "Today": 2.21},
    {"name": "Microsoft Corp","ticker": "MSFT", "price": 259.58, "Today": 1.07},
    {"name": "Amazon.com Inc", "ticker": "AMZN", "price": 107.4, "Today": 3.35},
    {"name": "Alphabet Inc", "ticker": "GOOGL", "price": 2174.75, "Today": -4.51},
    {"name": "Alphabet Inc","ticker": "GOOG", "price": 2181.62, "Today": -5.81},
    {"name": "NVIDIA Corp", "ticker": "NVDA", "price": 159.82, "Today": -6.36},
    {"name": "Berkshire Hathaway inc","ticker": "BRK.B", "price": 277.5, "Today": 4.48},
    {"name": "Meta Platforms Inc", "ticker": "META", "price": 160.03, "Today":-1.22},
    {"name:": "UnitedHealth Group Inc","ticker": "UNH", "price": 517.4, "Today": 3.77},
    {"name": "Johnson & Johnson ", "ticker": "JNJ ", "price": 179.52, "Today": 2.01},
    {"name": "Visa Inc", "ticker": "V", "price": 107.4, "Today": 3.35},
    {"name": "Procter & Gamble Co", "ticker": "PG", "price": 146.11, "Today": 2.32},
    {"name": "Exxon Mobil Corp", "ticker": "XOM", "price": 87.55, "Today": 1.91},
    {"name": "Home Depot Inc", "ticker": "HD", "price": 279.08, "Today": 4.81},
    {"name": "Walmart Inc", "ticker": "WMT", "price": 122.63, "Today": 1.05},
    {"name": "Chevron Corporation", "ticker": "CVX", "price": 107.4, "Today": 1.73},
    {"name": "Mastercard Inc", "ticker": "MA", "price": 318.24, "Today": 2.76},
    {"name": "Bank of America Corp", "ticker": "BAC", "price": 31.56, "Today":0.43 },
    {"name": "AbbVie Inc", "ticker": "ABBV", "price": 153.80, "Today": 0.64},
    {"name": "Pfizer Inc.", "ticker": "PFE", "price": 52.31, "Today": -0.12},
    {"name": "Broadcom Inc", "ticker": "AVGO", "price":477.84, "Today": -7.97},
    {"name": "Costco Wholesale Corporation", "ticker": "COST", "price": 485.76, "Today":6.48},
    {"name": "Walt Disney Co", "ticker": "DIS", "price": 96.14, "Today": 1.74},
    {"name": "Coca-Cola Co", "ticker": "KO", "price": 64.38, "Today": 1.47},
    {"name": "JPMorgan Chase & Co", "ticker": "JPM", "price": 114.05, "Today": 1.44},
]
export const tech = [ {"name": "Hewlett Packard Enterprise Co", "ticker": "HPE", "price": 12.96, "Today": -0.30},
{"name": "Mandiant Inc","ticker": "MNDT", "price": 21.82, "Today": 0.00},
{"name": "Arrow Electronics, Inc.", "ticker": "ARW", "price": 111.76, "Today": -0.33},
{"name": "Service Properties Trust", "ticker": "HPO", "price": 5.07, "Today": 0.24},
{"name": "Intel Corporation","ticker": "INTC", "price": 2181.62, "Today": -5.81},
{"name": "Godaddy Inc", "ticker": "GDDY", "price": 70.87, "Today": 1.40},
{"name": "Black Knight Inc","ticker": "BKI", "price": 66.18, "Today": 0.79},
{"name": "TD Synnex Corp", "ticker": "SNX", "price": 92.43, "Today":1.33},
{"name:": "National Instruments Corp","ticker": "NATI", "price": 31.02, "Today": -0.21},
{"name": "ON Semiconductor Corp", "ticker":  "ON", "price": 46.84, "Today": -3.47},
{"name": "Switch Inc", "ticker": "SWCH" ,"price": 33.45, "Today": -0.050},
{"name": "Aspen Technology Inc", "ticker": "AZPN", "price": 191.24, "Today": 7.56},
{"name": "Palo Alto Networks Inc", "ticker": "PANW", "price": 508.25, "Today": 14.31},
{"name": "Pure Storage Inc", "ticker": "PSTG" , "price": 24.76, "Today": -0.95},
{"name": "Digi International Inc", "ticker": "DGI", "price": 23.00, "Today": 0.40},
]
export const auto = [
    {"name": "Tesla Inc", "ticker": "TSLA", "price": 681.79, "Today": 1.24},
    {"name": "General Motors Company","ticker": "GM", "price":32.19, "Today": 0.43},
    {"name": "Ford Motor Company", "ticker": "F", "price": 11.32, "Today": 0.18},
    {"name": "Toyota Motor Corp", "ticker": "TM", "price": 155.47, "Today": 1.30},
    {"name": "CarMax, Inc","ticker": "KMX", "price": 92.67, "Today": 2.19},
    {"name": "Carvana Co", "ticker": "CVNA", "price": 21.87, "Today": -0.71},
    {"name": "Ferrari NV","ticker": "RACE", "price": 187.94, "Today": 4.46},
    {"name": "Stellantis NV", "ticker": "STLA", "price": 12.40, "Today":0.04},
    {"name:": "Nio Inc - ADR","ticker": "NIO", "price": 21.36, "Today": 0.36},
    {"name": "HMC ", "ticker": "Honda Motor Co Ltd", "price": 24.21, "Today": 0.06},
]
